import HalfIcon from "../assets/icons/HalfIcon";
import NoStarIcon from "../assets/icons/NoStarIcon";
import StarIcon from "../assets/icons/StarIcon";

export const ourprodact = [
    {
        id: 1,
        image: '/images/our-prodact-img-1.png',
        title: 'Breed Dry Dog Food',
        newPrice: '$100',
        reviews:'(35)',
        icon: <StarIcon/>,
        icon2: <StarIcon/>,
        icon3: <StarIcon/>,
        icon4: <NoStarIcon/>,
        icon5: <NoStarIcon/>,
    },
    {
        id: 2,
        image: '/images/our-prodact-img-2.png',
        title: 'CANON EOS DSLR Camera',
        newPrice: '$360',
        reviews:'(95)',
        icon: <StarIcon/>,
        icon2: <StarIcon/>,
        icon3: <StarIcon/>,
        icon4: <StarIcon/>,
        icon5: <NoStarIcon/>,
    },
    {
        id: 3,
        image: '/images/our-prodact-img-3.png',
        title: 'ASUS FHD Gaming Laptop',
        newPrice: '$700',
        reviews:'(321)',
        icon: <StarIcon/>,
        icon2: <StarIcon/>,
        icon3: <StarIcon/>,
        icon4: <StarIcon/>,
        icon5: <StarIcon/>,

    },
    {
        id: 4,
        image: '/images/our-prodact-img-4.png',
        title: 'Curology Product Set ',
        newPrice: '$500',
        reviews:'(145)',
        icon: <StarIcon/>,
        icon2: <StarIcon/>,
        icon3: <StarIcon/>,
        icon4: <StarIcon/>,
        icon5: <NoStarIcon/>,
    },
    {
        id: 5,
        image: '/images/our-prodact-img-5.png',
        title: 'Curology Product Set ',
        newPrice: '$500',
        reviews:'(65)',
        icon: <StarIcon/>,
        icon2: <StarIcon/>,
        icon3: <StarIcon/>,
        icon4: <StarIcon/>,
        icon5: <StarIcon/>,
    },
    {
        id: 6,
        image: '/images/our-prodact-img-6.png',
        title: 'Curology Product Set ',
        newPrice: '$500',
        reviews:'(35)',
        icon: <StarIcon/>,
        icon2: <StarIcon/>,
        icon3: <StarIcon/>,
        icon4: <StarIcon/>,
        icon5: <StarIcon/>,
    },
    {
        id: 7,
        image: '/images/our-prodact-img-7.png',
        title: 'Curology Product Set ',
        newPrice: '$500',
        reviews:'(55)',
        icon: <StarIcon/>,
        icon2: <StarIcon/>,
        icon3: <StarIcon/>,
        icon4: <StarIcon/>,
        icon5: <HalfIcon/>,
    },
    {
        id: 8,
        image: '/images/our-prodact-img-8.png',
        title: 'Curology Product Set ',
        newPrice: '$500',
        reviews:'(55)',
        icon: <StarIcon/>,
        icon2: <StarIcon/>,
        icon3: <StarIcon/>,
        icon4: <StarIcon/>,
        icon5: <HalfIcon/>,
    },
]