import HalfIcon from "../assets/icons/HalfIcon";
import NoStarIcon from "../assets/icons/NoStarIcon";
import StarIcon from "../assets/icons/StarIcon";

export const thismonth = [
  {
    id: 1,
    image: "/images/thes-img-1.png",
    text: "The north coat",
    newPrice: "$260",
    oldPrice: "$360",
    icon: <StarIcon />,
    icon2: <StarIcon />,
    icon3: <StarIcon />,
    icon4: <StarIcon />,
    icon5: <StarIcon />,
    Reviews: "(150 Reviews)",
    Stock: "In Dress",
  },
  {
    id: 2,
    image: "/images/thes-img-2.png",
    text: "Gucci duffle bag",
    newPrice: "$960",
    oldPrice: "$1160",
    icon: <StarIcon />,
    icon2: <StarIcon />,
    icon3: <StarIcon />,
    icon4: <StarIcon />,
    icon5: <HalfIcon />,
    Reviews: "(130 Reviews)",
    Stock: "In Bag",
  },
  {
    id: 3,
    image: "/images/thes-img-3.png",
    text: "RGB liquid CPU Cooler",
    newPrice: "$160",
    oldPrice: "$170",
    icon: <StarIcon />,
    icon2: <StarIcon />,
    icon3: <StarIcon />,
    icon4: <StarIcon />,
    icon5: <HalfIcon />,
    Reviews: "(110 Reviews)",
    Stock: "In Kalonka",
  },
  {
    id: 4,
    image: "/images/thes-img-4.png",
    text: "Small BookSelf",
    newPrice: "$360",
    oldPrice: "",
    icon: <StarIcon />,
    icon2: <StarIcon />,
    icon3: <StarIcon />,
    icon4: <StarIcon />,
    icon5: <HalfIcon />,
    Reviews: "(120 Reviews)",
    Stock: "In A chair",
  },
];