import HalfIcon from "../assets/icons/HalfIcon";
import NoStarIcon from "../assets/icons/NoStarIcon";
import StarIcon from "../assets/icons/StarIcon";

export const today = [
  {
    id: 1,
    image: "/images/today-image-1.png",
    title: "HAVIT HV-G92 Gamepad",
    newPrice: "$120",
    oldPrice: "$160",
    discount: "-40%",
    icon: <StarIcon />,
    icon2: <StarIcon />,
    icon3: <StarIcon />,
    icon4: <StarIcon />,
    icon5: <StarIcon />,
    Reviews: "110 Reviews",
    Stock: "In Gamepad",
    donk: '$1500'
  },
  {
    id: 2,
    image: "/images/today-image-2.png",
    title: "AK-900 Wired Keyboard",
    newPrice: "$960",
    oldPrice: "$1160",
    discount: "-35%",
    icon: <StarIcon />,
    icon2: <StarIcon />,
    icon3: <StarIcon />,
    icon4: <StarIcon />,
    icon5: <NoStarIcon />,
    Reviews: "150 Reviews",
    Stock: "In Keybord",
    donk: '$380'
  },
  {
    id: 3,
    image: "/images/today-image-3.png",
    title: "HAVIT HV-G92 Gamepad",
    newPrice: "$120",
    oldPrice: "$160",
    discount: "-30%",
    icon: <StarIcon />,
    icon2: <StarIcon />,
    icon3: <StarIcon />,
    icon4: <StarIcon />,
    icon5: <StarIcon />,
    Reviews: "101 Reviews",
    Stock: "In Tv",
    donk: '$100'
  },
  {
    id: 4,
    image: "/images/today-image-4.png",
    title: "IPS LCD Gaming Monitor",
    newPrice: "$370",
    oldPrice: " $400",
    discount: "-25%",
    icon: <StarIcon />,
    icon2: <StarIcon />,
    icon3: <StarIcon />,
    icon4: <StarIcon />,
    icon5: <HalfIcon />,
    Reviews: "90 Reviews",
    Stock: "In chair",
    donk: '$600'
  },
  {
    id: 5,
    image: "/images/today-image-4.png",
    title: "IPS LCD Gaming Monitor",
    newPrice: "$370",
    oldPrice: " $400",
    discount: "-25%",
    icon: <StarIcon />,
    icon2: <StarIcon />,
    icon3: <StarIcon />,
    icon4: <StarIcon />,
    icon5: <HalfIcon />,
    Reviews: "80 Reviews",
    Stock: "In A chair",
    donk: '$500'
  },
  {
    id: 6,
    image: "/images/today-image-4.png",
    title: "IPS LCD Gaming Monitor",
    newPrice: "$370",
    oldPrice: " $400",
    discount: "-25%",
    icon: <StarIcon />,
    icon2: <StarIcon />,
    icon3: <StarIcon />,
    icon4: <StarIcon />,
    icon5: <HalfIcon />,
    Reviews: "50 Reviews",
    Stock: "In A chair",
    donk: '$570'
  },
];